### ISSUE TITLE
RuntimeError: no running event loop (when running Plot)

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#65]
I was able to set up conda and snakemake on another (Intel) Macbook Pro laptop (this time with `brew install mamba` instead of the usual installation with conda and conda-forge which didn't work for reasons that have to do with @rpath/libarchive.13.dyli not being loaded properly.

With this setup, I was able to run GRAPEVNE from the command line within the conda base environment as we did during the demo. And I was able to run "BUILD AND TEST", however only with the "Download" and "Filter" modules. When I add another module, e.g. "Plot", I get the following error message:

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/common/__init__.py", line 69, in async_run
    _ = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/__init__.py", line 793, in snakemake
    success = workflow.execute(
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/workflow.py", line 896, in execute
    dag.init()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/dag.py", line 239, in init
    self.update_needrun(create_inventory=True)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/dag.py", line 1047, in update_needrun
    self.workflow.iocache.mtime_inventory(self.jobs)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 136, in mtime_inventory
    async_run(self._mtime_inventory(jobs))
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/common/__init__.py", line 71, in async_run
    asyncio.run(coroutine)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 175, in _mtime_inventory
    await asyncio.gather(*tasks)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 156, in worker
    raise e
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 152, in worker
    self.mtime[item] = await self.collect_mtime(item)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 178, in collect_mtime
    return path.mtime_uncached
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 499, in mtime_uncached
    mtime_remote = self.remote_object.mtime() if self.is_remote else None
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/remote/webdav.py", line 120, in mtime
    if self.exists():
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/remote/webdav.py", line 117, in exists
    return self.loop.run_until_complete(self.conn.exists(self.webdav_file))
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 586, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'Client.exists' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x107f85720>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x107f3a260>, 977304.180687181)]']
connector: <aiohttp.connector.TCPConnector object at 0x107f846a0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x107f87c70>
transport: <_SelectorSocketTransport closing fd=13>
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
testbuild > ls
benchmark       config          results         workflow
testbuild > ls results/
tutorialbuilder_download
testbuild > rm -rf results/
testbuild > cd /Users/joetsui/workflows/testbuild
orkflow/Snakefile --cores 1 --use-conda $(snakemake --list)testbuild/w 
Building DAG of jobs...
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/common/__init__.py", line 69, in async_run
    _ = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/__init__.py", line 793, in snakemake
    success = workflow.execute(
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/workflow.py", line 896, in execute
    dag.init()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/dag.py", line 239, in init
    self.update_needrun(create_inventory=True)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/dag.py", line 1047, in update_needrun
    self.workflow.iocache.mtime_inventory(self.jobs)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 136, in mtime_inventory
    async_run(self._mtime_inventory(jobs))
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/common/__init__.py", line 71, in async_run
    asyncio.run(coroutine)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 175, in _mtime_inventory
    await asyncio.gather(*tasks)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 156, in worker
    raise e
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 152, in worker
    self.mtime[item] = await self.collect_mtime(item)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 178, in collect_mtime
    return path.mtime_uncached
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/io.py", line 499, in mtime_uncached
    mtime_remote = self.remote_object.mtime() if self.is_remote else None
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/remote/webdav.py", line 120, in mtime
    if self.exists():
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/snakemake/remote/webdav.py", line 117, in exists
    return self.loop.run_until_complete(self.conn.exists(self.webdav_file))
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 586, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'Client.exists' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1123fd8a0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x1123b1f60>, 977334.168406108)]']
connector: <aiohttp.connector.TCPConnector object at 0x1123fd1e0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x1123ffa30>
transport: <_SelectorSocketTransport closing fd=13>
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by joetsui1994** [comment]
I am able to reproduce the error with Python3.9.

**Comment by jsbrittain** [comment]
The Download and Filter modules use a different syntax to download remote files than the plot method (all download remote files for either their config or scripts). This was done partially to test the different methods while I implemented a built-in version of snakemake (no need to run from the command line), which should now be done. Note however that I have not yet built this version of the app into binaries for quick install (so they require a build from source). I have patchy internet at the moment but will try to address this in the next couple of days and provide an update.

**Comment by jsbrittain** [comment]
@joetsui1994 a new build of snakemake is available [https://github.com/kraemer-lab/GRAPEVNE/releases](https://github.com/kraemer-lab/GRAPEVNE/releases). Could you try this again as I have run the tutorial workflow through and it seems to work on my system.

**Comment by joetsui1994** [comment]
@jsbrittain I tried running it from cmdline and got the following error:
```
snakemake.exceptions.WorkflowError: The Python 3 package 'boto3' needs to be installed to use S3 remote() file functionality. No module named 'boto3'
[16565] Failed to execute script 'backend' due to unhandled exception!
```
Are we now using s3 buckets?

**Comment by jsbrittain** [comment]
@joetsui1994 We are not using s3 buckets, but I did enable them in anticipation that others would be. Looks like a missing dependency with the version of python/snakemake that is bundled with the app. Should be a straightforward fix. I will amend and test. In the meantime it should be possible to switch to the 'system' installed version of snakemake from the settings panel.

**Comment by joetsui1994** [comment]
@jsbrittain I see. I just tried switching snakemake from "Built-in" to "System" and the issue remains. It doesn't seem to matter whether I have boto3 installed in my conda base environment either. The error message seems to be exactly the same for both "Built-in" and "System".

**Comment by jsbrittain** [comment]
@joetsui1994 Ah, okay. The 'Get Modules List' function uses the python backend, which could cause it to fail if there are missing dependencies (although I am surprised by this error as it does not reproduce with a clean install on my machine).

Can I ask:
1. What is your OS, type of machine?
2. There will be a log file ("GRAPEVNE.log") generated in your home folder - can you send that over to me?
3. To see if we can resolve the error on your machine, could you try a build from source (`build.sh`) with the following amendment in 'electron-app/build_deps.sh' to remove unnecessary remote file support; specifically, shorten the `python -m PyInstaller` lines to...
```bash
python -m PyInstaller src/python/backend.py \
    --onefile \
    --hidden-import builder \
    --hidden-import runner \
    --hidden-import smart_open.http
```

**Comment by jsbrittain** [comment]
Removing additional `snakemake.remote` PyInstaller dependencies resolved the immediate issue, but then failed due to a missing dependency (on a fresh install) for successful compilation of `cairo`/`node-canvas` within `nodemapper` (issue could be ARM-specific). Both the `node-canvas` and comprehensive `snakemake.remote` dependencies are included in PR #73 , so that full remote functionality is retained within Snakemake workflow files.

**Comment by jsbrittain** [comment]
[GRAPEVNE v0.0.4](https://github.com/kraemer-lab/GRAPEVNE/releases/tag/v0.0.4) resolves this issue.
@joetsui1994 can you confirm on your machine? Thanks.
